### ISSUE TITLE
Code format and style

### ISSUE THREAD

**Issue by wdotmathree** [sireButItsUnique/erosion-compiler#1]
Remove spaces in folder names and make better distinctions between purposes of header and source files.

**Comment by sireButItsUnique** [comment]
We'll fix that after I fix my brightness

**Comment by pepeworm** [comment]
That's never happening @sireButItsUnique

**Comment by wdotmathree** [comment]
fine ill do it myself just merge my pr later good luck with merge conflicts

**Comment by wdotmathree** [comment]
also unmark this as duplicate
