### ISSUE TITLE
Spaces in folder names

### ISSUE THREAD

**Issue by kevlu8** [sireButItsUnique/erosion-compiler#2]
W-while weading thwough youw wepo, I noticed that you haf spaces in youw fowlder names~

Spaces awe genewally used as dewimiters, and so dis iws bad pwactice...

Fow the sake of my eyes and evewyone elses eyes, pwease change the fowlder names to not contain spaces~!

Thank you senpai~

**Comment by sireButItsUnique** [comment]
Sowwy we will fwix as swoon as pwossible
